### ISSUE TITLE
Syntax error when running with openjdk 21

### ISSUE THREAD

**Issue by TimoKramer** [borgeby/jarl#177]
I am getting
```
Syntax error macroexpanding at (time.cljc:88:6).
Execution error (NullPointerException) at jarl.time/fn (time.cljc:89).
Cannot invoke "java.lang.Character.charValue()" because "x" is null
```
seems because `(System/getProperty "java.vm.version")` returns `21+35` for me and that can not be passed in the following function where you try to get the index of `.`.

**Comment by anderseknert** [comment]
Thanks for reporting that Timo! Haven't had the time to try this with Java 21 yet. Seems like you've found the cause on your own. Would you want to submit a fix? :)
